version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - test